name: lint
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    name: lint ${{matrix.dir}}
    strategy:
      matrix:
        elixir: ['1.12.2']
        otp: ['24']
    steps:
    - uses: actions/checkout@v2

    - name: Setup elixir
      uses: erlef/setup-elixir@v1
      with:
        elixir-version: ${{ matrix.elixir }} # Define the elixir version [required]
        otp-version: ${{ matrix.otp }} # Define the OTP version [required]

    - name: Retrieve Mix Dependencies Cache
      uses: actions/cache@v1
      id: mix-cache #id to use in retrieve action
      with:
        path: deps
        key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

    - if: steps.deps-cache.outputs.cache-hit != 'true'
      working-directory: ${{ matrix.dir }}
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
        mix deps.compile

    - run: mix format --check-formatted
      working-directory: ${{ matrix.dir }}

    - run: mix compile --warnings-as-errors
      working-directory: ${{ matrix.dir }}

    - run: mix credo
      working-directory: ${{ matrix.dir }}
